/**
 * Tests for the centralized Pi self-update check (`src/pi-update.ts`).
 *
 * Every test spawns a small stub `pi` generated by `writeStubPi` -- no real host binary is
 * ever invoked, and no test relies on ambient environment: `ensurePiCurrent` always receives
 * an explicit `env` (at minimum `{}`), so a `COUNCIL_PI_BIN`, `COUNCIL_NO_PI_UPDATE`, or
 * `PI_OFFLINE` leaked into the test runner's own environment can neither break nor
 * silently skip these tests.
 */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { ensurePiCurrent, parsePiVersion, PI_SELF_UPDATE_ARGS } from '../../src/pi-update.js';

let dir: string;

beforeEach(() => {
  dir = fs.mkdtempSync(path.join(os.tmpdir(), 'council-pi-update-test-'));
});

afterEach(() => {
  fs.rmSync(dir, { recursive: true, force: true });
});

interface StubOpts {
  /** Exact stdout for `--version`; when absent, `--version` reads `versionFile` instead. */
  versionStdout?: string;
  /** File holding the current version text; `update` rewrites it when `updateBumpTo` is set. */
  versionFile?: string;
  versionExit?: number;
  versionDelayMs?: number;
  updateExit?: number;
  updateDelayMs?: number;
  /** When set (with `versionFile`), `update` rewrites the version file to this. */
  updateBumpTo?: string;
  /** When set, `update` appends its received argv (one JSON array per line) here. */
  updateLog?: string;
}

/**
 * Writes a stub `pi` binary: `--version` reports a version, `update` optionally bumps it,
 * anything else exits 2. A synchronous sleep (`Atomics.wait`) implements the delay knobs
 * without any dependency.
 */
function writeStubPi(name: string, opts: StubOpts = {}): string {
  const p = path.join(dir, name);
  const versionBranch =
    opts.versionStdout !== undefined
      ? `process.stdout.write(${JSON.stringify(opts.versionStdout)});`
      : opts.versionFile !== undefined
        ? `process.stdout.write(fs.readFileSync(${JSON.stringify(opts.versionFile)}, 'utf8'));`
        : `process.stdout.write('9.9.9\\n');`;
  const script = `#!/usr/bin/env node
const fs = require('node:fs');
const args = process.argv.slice(2);
const sleep = (ms) => { if (ms > 0) Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms); };
if (args[0] === '--version') {
  sleep(${opts.versionDelayMs ?? 0});
  ${versionBranch}
  process.exit(${opts.versionExit ?? 0});
}
if (args[0] === 'update') {
  sleep(${opts.updateDelayMs ?? 0});
  ${opts.updateLog !== undefined ? `fs.appendFileSync(${JSON.stringify(opts.updateLog)}, JSON.stringify(args) + '\\n', 'utf8');` : ''}
  ${opts.updateBumpTo !== undefined && opts.versionFile !== undefined ? `fs.writeFileSync(${JSON.stringify(opts.versionFile)}, ${JSON.stringify(opts.updateBumpTo)}, 'utf8');` : ''}
  process.exit(${opts.updateExit ?? 0});
}
process.exit(2);
`;
  fs.writeFileSync(p, script, { mode: 0o755 });
  return p;
}

function writeVersionFile(name: string, content: string): string {
  const p = path.join(dir, name);
  fs.writeFileSync(p, content, 'utf8');
  return p;
}

describe('parsePiVersion', () => {
  it('parses a bare version', () => {
    expect(parsePiVersion('0.87.1\n')).toBe('0.87.1');
  });

  it('strips a leading v', () => {
    expect(parsePiVersion('v0.87.1')).toBe('0.87.1');
  });

  it('keeps a pre-release suffix', () => {
    expect(parsePiVersion('1.0.0-beta.1\n')).toBe('1.0.0-beta.1');
  });

  it('finds the version among banner lines', () => {
    expect(parsePiVersion('[Some Extension] tools registered\n0.87.1\n')).toBe('0.87.1');
  });

  it('rejects a JSON event stream (what a test double replays when it does not model --version)', () => {
    expect(
      parsePiVersion('{"type":"message_start","role":"assistant"}\n{"type":"text_end"}\n'),
    ).toBeNull();
  });

  it('rejects prose that merely contains a version', () => {
    expect(parsePiVersion('pi is already up to date (v0.87.1)\n')).toBeNull();
  });

  it('rejects empty output', () => {
    expect(parsePiVersion('')).toBeNull();
  });
});

describe('ensurePiCurrent', () => {
  it('reports already-latest when the version is unchanged, invoking update self-only', async () => {
    const versionFile = writeVersionFile('version.txt', '1.2.3\n');
    const updateLog = path.join(dir, 'update.log');
    const piBin = writeStubPi('pi.cjs', { versionFile, updateLog });

    const result = await ensurePiCurrent({ piBin, env: {} });

    expect(result).toEqual({
      status: 'already-latest',
      previousVersion: '1.2.3',
      currentVersion: '1.2.3',
      reason: null,
    });
    // The update scope, pinned: exactly `update --self` -- never `--all`, `--extensions`,
    // `--models`, or a named extension source.
    const invocations = fs
      .readFileSync(updateLog, 'utf8')
      .trim()
      .split('\n')
      .map((line) => JSON.parse(line) as string[]);
    expect(invocations).toEqual([[...PI_SELF_UPDATE_ARGS]]);
    expect(PI_SELF_UPDATE_ARGS).toEqual(['update', '--self']);
  });

  it('reports updated when the version changed across the update', async () => {
    const versionFile = writeVersionFile('version.txt', '1.2.3\n');
    const piBin = writeStubPi('pi.cjs', { versionFile, updateBumpTo: '1.2.4\n' });

    const result = await ensurePiCurrent({ piBin, env: {} });

    expect(result).toEqual({
      status: 'updated',
      previousVersion: '1.2.3',
      currentVersion: '1.2.4',
      reason: null,
    });
  });

  it('resolves the host binary from COUNCIL_PI_BIN when no override is given', async () => {
    const versionFile = writeVersionFile('version.txt', '2.0.0\n');
    const stub = writeStubPi('pi.cjs', { versionFile });

    const result = await ensurePiCurrent({ env: { COUNCIL_PI_BIN: stub } });

    expect(result.status).toBe('already-latest');
    expect(result.currentVersion).toBe('2.0.0');
  });

  it('skips without spawning when COUNCIL_NO_PI_UPDATE=1', async () => {
    const result = await ensurePiCurrent({
      // Nonexistent on purpose: a spawn would surface as failed/spawn-failed, so skipped
      // proves nothing was spawned.
      piBin: path.join(dir, 'no-such-pi'),
      env: { COUNCIL_NO_PI_UPDATE: '1' },
    });

    expect(result).toEqual({
      status: 'skipped',
      previousVersion: null,
      currentVersion: null,
      reason: 'opted-out',
    });
  });

  it('skips without spawning when PI_OFFLINE=1', async () => {
    const result = await ensurePiCurrent({
      piBin: path.join(dir, 'no-such-pi'),
      env: { PI_OFFLINE: '1' },
    });

    expect(result).toEqual({
      status: 'skipped',
      previousVersion: null,
      currentVersion: null,
      reason: 'offline',
    });
  });

  it('fails without throwing when the binary is missing', async () => {
    const result = await ensurePiCurrent({ piBin: path.join(dir, 'no-such-pi'), env: {} });

    expect(result).toEqual({
      status: 'failed',
      previousVersion: null,
      currentVersion: null,
      reason: 'spawn-failed',
    });
  });

  it('fails when --version exits non-zero', async () => {
    const piBin = writeStubPi('pi.cjs', { versionStdout: '1.2.3\n', versionExit: 1 });

    const result = await ensurePiCurrent({ piBin, env: {} });

    expect(result.status).toBe('failed');
    expect(result.reason).toBe('version-exit-nonzero');
  });

  it('fails without attempting an update when --version output is unparseable', async () => {
    const updateLog = path.join(dir, 'update.log');
    const piBin = writeStubPi('pi.cjs', {
      versionStdout: '{"type":"message_start"}\n',
      updateLog,
    });

    const result = await ensurePiCurrent({ piBin, env: {} });

    expect(result).toEqual({
      status: 'failed',
      previousVersion: null,
      currentVersion: null,
      reason: 'version-unparseable',
    });
    expect(fs.existsSync(updateLog)).toBe(false);
  });

  it('fails when --version hangs past its timeout', async () => {
    const piBin = writeStubPi('pi.cjs', { versionStdout: '1.2.3\n', versionDelayMs: 5000 });

    const result = await ensurePiCurrent({ piBin, env: {}, versionTimeoutMs: 50 });

    expect(result.status).toBe('failed');
    expect(result.reason).toBe('version-timeout');
  });

  it('fails with the pre-update version when update exits non-zero', async () => {
    const versionFile = writeVersionFile('version.txt', '1.2.3\n');
    const piBin = writeStubPi('pi.cjs', { versionFile, updateExit: 1 });

    const result = await ensurePiCurrent({ piBin, env: {} });

    expect(result).toEqual({
      status: 'failed',
      previousVersion: '1.2.3',
      currentVersion: '1.2.3',
      reason: 'update-exit-nonzero',
    });
  });

  it('fails with the pre-update version when update hangs past its timeout', async () => {
    const versionFile = writeVersionFile('version.txt', '1.2.3\n');
    const piBin = writeStubPi('pi.cjs', { versionFile, updateDelayMs: 5000 });

    const result = await ensurePiCurrent({ piBin, env: {}, updateTimeoutMs: 50 });

    expect(result).toEqual({
      status: 'failed',
      previousVersion: '1.2.3',
      currentVersion: '1.2.3',
      reason: 'update-timeout',
    });
  });

  it('fails when the post-update version is unparseable', async () => {
    const versionFile = writeVersionFile('version.txt', '1.2.3\n');
    const piBin = writeStubPi('pi.cjs', { versionFile, updateBumpTo: 'garbage\n' });

    const result = await ensurePiCurrent({ piBin, env: {} });

    expect(result).toEqual({
      status: 'failed',
      previousVersion: '1.2.3',
      currentVersion: '1.2.3',
      reason: 'post-version-unparseable',
    });
  });
});
